# Generated by Django 6.0.1 on 2026-06-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "author",
                    models.CharField(blank=True, max_length=120, verbose_name="Autor"),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("article", "Artículo"),
                            ("book", "Libro"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("document", "Documento"),
                        ],
                        default="article",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("url", models.URLField(verbose_name="Enlace")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Destacado"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publicado"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Recurso",
                "verbose_name_plural": "Recursos",
                "ordering": ["-is_featured", "-created"],
            },
        ),
    ]
